### ISSUE TITLE
NullPointerException after asking about Architecture

### ISSUE THREAD

**Issue by phunni** [MCMrARM/google_play_downloader#2]
This is the "transcript" of my attempt to run:

`java -jar ~/downloads/misc/playdl.jar 
Email: ************@gmail.com
Password: ****************
Language [en]: 
Do you want to use x86 as the architecture? [y/N]: y
Exception in thread "main" java.lang.NullPointerException
    at com.github.mcmrarm.playdl.proto.GooglePlay$AndroidCheckinRequest$Builder.addAccountCookie(GooglePlay.java)
    at com.github.mcmrarm.playdl.CheckinManager.getRequest(CheckinManager.java:232)
    at com.github.mcmrarm.playdl.CheckinManager.execRequest(CheckinManager.java:253)
    at com.github.mcmrarm.playdl.CheckinManager.getAndroidId(CheckinManager.java:287)
    at com.github.mcmrarm.playdl.Main.main(Main.java:38)
`

**Comment by phunni** [comment]
It appears to be a NullPointer here: 

`.addAccountCookie(myLogin.getAuth())` Line 232 of CheckinManager - due (as far as I can see) to myLogin geing null, presumably because getRequest() is being called before login()?

**Comment by ghost** [comment]
I am having the exact same problem. Please tell me if you have resolved it, thanks.

**Comment by Matsv** [comment]
I have the same problem.
Could it be caused by having 2fa enabled?

**Comment by phunni** [comment]
Still having this problem - has anyone managed to solve it?

**Comment by ghost** [comment]
I think that you need to remove the session txt file that the program made. Run the jar in a new folder.
