### ISSUE TITLE
Error after entering account data

### ISSUE THREAD

**Issue by SalmonDE** [MCMrARM/google_play_downloader#6]
I entered my account data and typed in y when it asked me for x86 architecture. Then it crashed.
Here are the errors:

`Do you want to use x86 as the architecture? [y/N]: y
Exception in thread "main" java.lang.NullPointerException
        at com.github.mcmrarm.playdl.proto.GooglePlay$AndroidCheckinRequest$Builder.addAccountCookie(GooglePlay.java)
        at com.github.mcmrarm.playdl.CheckinManager.getRequest(CheckinManager.java:232)
        at com.github.mcmrarm.playdl.CheckinManager.execRequest(CheckinManager.java:253)
        at com.github.mcmrarm.playdl.CheckinManager.getAndroidId(CheckinManager.java:287)
        at com.github.mcmrarm.playdl.Main.main(Main.java:38)`

**Comment by SalmonDE** [comment]
Sorry, I didn't realize it's already reported
